### ISSUE TITLE
NE - Change how `Active set probability` is shown.

### ISSUE THREAD

**Issue by jessgess** [nymtech/team-product#335]
The labels currently presented in the mix node explorer are way off and give the wrong impression on many mix nodes. This is how the buckets should be presented:

Saturation > 15% --> Very high probability 
5% >= Saturation <15% --> Moderate probability 
Saturation < 5% --> Low probability 

_UPDATE:_

See comment below. It was decided that we should have 

    >= 70% -> high
    between (including) 30% to 70% -> good 
    <30% -> low

**Comment by mmsinclair** [comment]
Requires https://github.com/nymtech/team-core/issues/114 to be implemented correctly

**Comment by octol** [comment]
Update:

It was decided that we have three buckets:
>= 70% -> high
between (including) 30% to 70% -> good 
<30% -> low

**Comment by octol** [comment]
Raised https://github.com/nymtech/nym/pull/1626 to fix the last bits
